# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: dxheroes/dx-scanner:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Runs DX Scanner on the code
        run: dx-scanner run --ci
      
      - name: Reshift
        env:
          RESHIFT_TOKEN: ${{ secrets.RESHIFT_TOKEN }}
        run: npx @reshiftsecurity/reshift-plugin-npm -t ${RESHIFT_TOKEN} -l debug
